### ISSUE TITLE
关于异常：Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor

### ISSUE THREAD

**Issue by yuanchanglong1997** [LeonKou/NetPro#36]
**完整错误信息：**
Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: IDasContextAccessor Lifetime: Singleton ImplementationType: Das.Common.DasContextAccessor': Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Das.Common.DasContextAccessor'.)

InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Das.Common.DasContextAccessor

**原因分析：**
经调试后发现是项目中 NetPro.Web.Api中 RoutingStartup 执行报错导致 RoutingStartup 未能正确执行完毕，从而引起IHttpContextAccessor未被注入，最终导致这个问题的出现。在将 library中NetPro.Web.Api项目的RoutingStartup 源码拷贝下来执行调试后查看错误信息发现是这段代码报错了

```
mvcBuilder.AddFluentValidation(configuration =>           
{
                string assemblySkipLoadingPattern = "^NetPro.*|^Com.Ctrip*|^Figgle|^Serilog.*|^netstandard|^OpenTracing.Contrib.NetCor|^App.Metrics.AspNetCore|^SkyAPM|^Swashbuckle|^System|^mscorlib|^Microsoft|^AjaxControlToolkit|^Antlr3|^Autofac|^AutoMapper|^Castle|^ComponentArt|^CppCodeProvider|^DotNetOpenAuth|^EntityFramework|^EPPlus|^FluentValidation|^ImageResizer|^itextsharp|^log4net|^MaxMind|^MbUnit|^MiniProfiler|^Mono.Math|^MvcContrib|^Newtonsoft|^NHibernate|^nunit|^Org.Mentalis|^PerlRegex|^QuickGraph|^Recaptcha|^Remotion|^RestSharp|^Rhino|^Telerik|^Iesi|^TestDriven|^TestFu|^UserAgentStringLibrary|^VJSharpCodeProvider|^WebActivator|^WebDev|^WebGrease";
                var assembliesResult = new List<Assembly>();
                foreach (var item in assemblies)
                {
                    if (!Regex.IsMatch(item.FullName, assemblySkipLoadingPattern, RegexOptions.IgnoreCase | RegexOptions.Compiled) && Regex.IsMatch(item.FullName, ".*", RegexOptions.IgnoreCase | RegexOptions.Compiled))
                    {
                        if (!item.IsDynamic)
                            assembliesResult.Add(item);
                    }
                }
                configuration.RegisterValidatorsFromAssemblies(assembliesResult);

                //implicit/automatic validation of child properties 复合对象是否验证
                configuration.ImplicitlyValidateChildProperties = true;
 });

```
原因是NetPro本身有一个版本的SQLLite程序集，我在使用时又引入了SQLLite的其他版本程序集，而这里的正则表达式又没有排除搜索这两个，所以导致在注册的时候出现冲突

**解决办法：**
在配置文件中添加

`"TypeFinderOption": {
    "CustomDllPattern": "^XXX.Api*"
  }`

此配置表示仅搜索正则匹配到的程序集，此时只有一个版本的SQLLite，不再报错，问题解决。

**Comment by KamenRiderKuuga** [comment]
@yuanchanglong1997 在新版本中的`RoutingStartup`移除了`FluentValidation`的使用 #35 ，另外引入了`ReplaceStartup`注解，用于覆盖替换指定Startup，以便在遇到类似情况时绕开指定`Startup`的执行，详见：

https://github.com/LeonKou/NetPro/tree/dev_6.0/src/Library/NetPro.Startup
